[project]
name = "FASTAPI_project"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bcrypt==3.2.2",
    "fastapi[all]>=0.119.0",
    "passlib[bcrypt]==1.7.4",
    "psycopg>=3.2.10",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy>=2.0.44",
]
