[project]
name = "FASTAPI_project"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[all]>=0.119.0",
    "passlib[bcrypt]>=1.7.4",
    "psycopg>=3.2.10",
    "sqlalchemy>=2.0.44",
]
